import 'dart:ui';
import 'package:boysbrigade/utils.dart';

const LocaleBundle EN_US_BUNDLE = LocaleBundle(
    lang: 'English',
    locale: Locale('en', 'US'),
    trMap: <String, String>{
      'app title': "Hong Kong Boys' Brigade",
      'app subtitle': '78th Company',
      'app author': 'Melanie Hsieh',
      'title': 'BB78',
      'enter email': 'Enter email address',
      'enter password': 'Enter password',
      'login': 'Login',
      'half year': 'Half Year',
      'first half year': 'JAN - JUN',
      'second half year': 'JUL - DEC',
      '# of students': 'Students: ',
      'day': 'Day',
      'present': 'Present',
      'late': 'Late',
      'sick': 'Sick',
      'absent': 'Absent',
      'pe': 'PE',
      'attendance': 'Attendance',
      'uniform': 'Uniform',
      'marks': 'Marks',
      'cap': 'Cap',
      'vest': 'Vest',
      'others': 'Others',
      'shirt': 'Shirt',
      'pant': 'Pants',
      'shoes': 'Shoes',
      'belt': 'Belt',
      'tie': 'Tie',
      'submit': 'Submit',
      'save': 'Save',
      'cancel': 'Cancel',
      'settings': 'Settings',
      'about': 'About',
      'language': 'Language',
      'logout': 'Logout',
      'about app description':
          'As a CS14 member, I understand the struggle of not playing basketball but to count the number of participants and collect notice after the company section is dismissed. I hope to create a better afternoon.',
      'about app title': "Introducing Melanie Hsieh's masterpiece: BB78 App",
      'chinese': 'Chinese',
      'english': 'English',
      'n/a': 'N/A',
      'ok': 'Okay',
      'email required': 'Email required',
      'invalid email': 'Invalid email',
      'loading': 'Loading...',
      'done': 'Done',
      'prefer all student attendance':
          'Not all student attendance has been filled out. Are you sure you want to submit?',
      'need all teacher attendance':
          'You need to assign attendance for all teachers',
      'not available': 'Not Available :(',
      'password required': 'Password required',
      'login failed': 'Login failed!',
      'group not found': 'Specified group does not exist!',
      'saving data': 'Saving data...',
      'update': 'Update',
      'add new student': 'Enter name of new student',
      'remove existing student':
          'Are you sure you want to delete this student?',
      'nn': 'No Need',
      'signup': 'Signup',
    });
