import 'dart:ui';
import 'package:boysbrigade/utils.dart';

const LocaleBundle ZH_TW_BUNDLE = LocaleBundle(
  lang: '中文',
  locale: Locale('zh', 'TW'),
  trMap: <String, String>{
    'app title': '香港基督少年軍',
    'app subtitle': '第78分隊',
    'app author': '謝佩妏',
    'title': '78分隊',
    'enter email': '請輸入電郵地址',
    'enter password': '請輸入密碼',
    'login': '登入',
    'half year': '半年',
    'first half year': '1月 - 6月',
    'second half year': '7月 - 12月',
    '# of students': '人數:',
    'day': '當日',
    'present': '出席',
    'late': '遲到',
    'sick': '請假',
    'absent': '缺席',
    // TODO: get translation
    'pe': 'PE',
    'attendance': '出席率',
    'uniform': '制服',
    'marks': '分數',
    'cap': '鴨嘴帽',
    'vest': '背心',
    'others': '其他',
    'shirt': '襯衫',
    'pant': '裙/褲',
    'shoes': '皮鞋',
    'belt': '皮帶',
    'tie': '領帶',
    'submit': '提交',
    'settings': '設定',
    'about': '關於',
    'language': '語言',
    'logout': '登出',
    'about app description': '身為一位CS14的隊員，我深深地明白集隊後不能夠打籃球還要統計人數和收通告的痛苦。我希望能夠創造一個更加美好的下午。',
    'about app title': '隆重介紹 BB78 App 謝佩妏的傑作',
    'chinese': '中文',
    'english': '英文',
    'n/a': 'N/A',
    'ok': '好',
    'email required': '請輸入電郵地址',
    'invalid email': '電郵地址',
    'loading': '載入中',
    'done': '完成',
    'need all student attendance': '請輸入所有隊員的出席率',
    // TODO: get translation
    'need all teacher attendance': 'You need to assign attendance for all teachers',
    'not available': '沒有數據 :(',
    'password required': '請輸入密碼',
    'login failed': '登入失敗',
    'group not found': '此組別暫不存在',
    'saving data': '數據儲存中...',
    'update': '更新',
  }
);