import 'dart:ui';
import 'package:boysbrigade/utils.dart';

const LocaleBundle ZH_TW_BUNDLE = LocaleBundle(
    lang: '中文',
    locale: Locale('zh', 'TW'),
    trMap: <String, String>{
      'app title': '香港基督少年軍',
      'app subtitle': '第78分隊',
      'app author': '謝佩妏',
      'title': '78分隊',
      'enter email': '請輸入電郵地址',
      'enter password': '請輸入密碼',
      'login': '登入',
      'half year': '半年',
      'first half year': '1月 - 6月',
      'second half year': '7月 - 12月',
      '# of students': '人數:',
      'day': '當日',
      'unknown': '...',

      ///
      'present': '出席',
      'late': '遲到',
      'early': '早退',
      'sick': '請假',
      'absent': '缺席',
      'pe': '活動服',
      'late return': '請假(遲返)',
      'early leave': '請假(早退)',
      'personal leave': '事假',
      'sick leave': '病假',

      ///
      'attendance': '出席狀況',
      'uniform': '制服',
      'marks': '分數',
      'cap': '鴨嘴帽',
      'vest': '背心',
      'others': '其他',
      'shirt': '襯衫',
      'pant': '裙/褲',
      'shoes': '皮鞋',
      'belt': '皮帶',
      'tie': '領帶',
      'submit': '提交',
      'save': '儲存',
      'cancel': '取消',
      'settings': '設定',
      'about': '關於',
      'language': '語言',
      'logout': '登出',
      'about app description':
          '身為一名好動的CS14隊員，我非常理解散隊後不能馬上打籃球的痛苦。我希望能爭取更多打波的時間，除此以外減輕導師日常事務從而創造一個更美好的下午。',
      'about app title': '隆重介紹 BB78 HK App 謝佩妏的傑作',
      'chinese': '中文',
      'english': '英文',
      'n/a': 'N/A',
      'ok': '好',
      'email required': '請輸入電郵地址',
      'invalid email': '電郵地址錯誤',
      'loading': '載入中',
      'done': '完成',
      'prefer all student attendance': '隊員出席狀況並非完成，您是否確定要提交？',
      'need all teacher attendance': '導師出席狀況未完成',
      'not available': '沒有數據 :(',
      'password required': '請輸入密碼',
      'login failed': '登入失敗',
      'group not found': '此組別暫不存在',
      'saving data': '數據儲存中...',
      'update': '更新',
      'add new student': '新增隊員',
      'remove existing student': '您確定是否要移除此隊員？',
      'nn': '無需',
      'signup': '註冊',
    });
